language: java
sudo: required
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
- sudo apt-get install net-tools
- sudo apt-get install python-pip
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- test "${TRAVIS_PULL_REQUEST}" == "true" || test "${TRAVIS_BRANCH}" != "master" || ./gradlew bintrayUpload
- sudo pip install mkdocs
- mkdocs build
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ];then git remote add gh-token "https://$GITHUBKEY@github.com/yahoo/parsec";mkdocs gh-deploy --clean --remote-name gh-token;fi
after_success:
- ./gradlew coveralls
env:
  global:
  - secure: t/YmohP7hMuyGl6DcuRgPwUpm673SNKeFDegnEhikAK3155uMjQkbwqcbqzM6KTco0TVOVvoCDEp7C8DuJit8IYNgfXZdCo4nFS+XzzG8OtIy7RBRSWlwn/VaypTaqq6TFO+0Lvmo6oIyaT14D5M1eFwxpNie7Pjn9ycvZdMMcK/aUfTgRjvNiyFhZIT178JmzjdfpXsuTCp0eeK9mi/sQvT6zITIuyR9N61nvvcJiNENRidojH8jO8T1gL9QwcUrlJO95JuZ4o2uzFmlRxnPQj0qNJc9rEJJei9qFHvSz096FAxZFw9mE2OmFSiPmrn46nnxutfN9xsHn9ki3o+SjTlnY4h74fEcU/c4buFgoqRRHGRREQyDBbizMm3QL43Ze0S/bLvFhHY2K9tEhCYWmQWckKDPs+LbDtvfgyDyZpxovioMykmwSXbAB5TpVTtUG7Bit7KWj6dYwTVOYxPC1Do+JW2CsD9F8NR6yBTnmV5WF4tGPux2WOH6x3SkYr361J+eXA1hUF/VDWmATI0wsAlE/ZF14Efl05hle6hlraG/xzeNDbJA001QA4FWgDQO1Sv0TeJeeH7ydRUXcouCKJ+jo2XcLqBmL7SIW3We/55p3y4Y2q/0lTefOVECdTcfHgjB5monhyINIfkozotuZ+ugjzl6ON+nBxk07chvXE=
  - secure: dnjdsBcnrLAV0fNC/C9W0F6s2eU3ePLNfl9jGanBis9nZvyPNvAVyouaAv8AoSqaaRrQU6izf/wl0D2VhjSVksQpOwDj4t1EjrYi8S/FKYk3Vbsc4/1q9/sXzZBUYEYAAy2mce50lC0knBlCqsEcFUKoNlA7pbvUjE/uOknCp8zioXf1Cjz3aMfXdX5U/r/5I4FOYulBoDt9PGOlKe3jylO14AQCSWEnuT6sXe19VxtVkMShrWPloJJa3bYoMvt+lMqbjTHCWB0xjCYhQEPP9Qah8WgrXGGpcOYsu7JtXbzziCDGdLRPz/CFcukeOsytysG5GiNheNJQ9YnCw6o+TmOD9ym2ZyVVbUty2Jkh/xYfR/fRaOrG+rSwgGODv1Oc66G8MZOzo4bIeS1NcO5w0HHlR+luagljI5Sf7oydUj87SwW04oS/vwnm1RAXEHIk8jhyPIBiBekyRWnIRVtZZPjSs9Z8Mf3CMQjQ3wcxmpmBMzS8CnkPqtvorWxXF7rGkFaUXZNYooL5uIcnFi9cIjpanxhnAEIuMn7E+sYiCfxYPxYSkq8bC44DeLXPtL9LbXcZVtK8kxLP4Z3Eoy1nev4OykJthC0XKu3XNDufpGRh/47le/+syhIb5T4tOAtiYF95w9pGOBZ0KlfTP2jMOLiRGliaN4fp8+T/9Q9E/CM=
  - secure: BU2qoM9lROCFnBFK+LqXEJJm/nIulkAbpiw+8Mn7cN6LRD+PYZ0IVnQmHskALEWTzpkBt1AxO+WG19UCgqLGrFV2g0V/vzYKf2F2Xmslsk9/5ncF2zWFIHbSfn/mXNFx4kKiJ6tUjEI02xz/FT4YIp7g2qk18akpCvlaSkqQ7FDRbNkRgusWLqzBT3jBh9fl6OTzhrJ4Y+9qJBjlphktrwPd/GspqJcEO0Vb9POy60lhexqg70fSd5YOrKnAv0br1g9QdxFG+p060moC+/81obrMc9X3q9jdVEQ1djDnSCmdNKTQP+0a9ux30dBClPOg6MtwzG8rncDUsfA50Btu9AQy+/BGRgCBnM4Rn2tKqsUvyHkdW0ST+dO1cdCtTQJj9yhlCticl1sqdlQ/49OxlX8znPXRDqED25wPwPTknFVzMAxUyqZA50Gr38X3jkMcCm0FF1LDjcyVH2Hs8pq/QUjD0OuvuMoecVbK8lPPMVXAvuLfBbVb24t3Qt30tq8w/LshPJIq/+GizQNrrakVR83w5vrpQzQft8wvqfqCkrJT85C/lknjON28Mi8d1KqzJ+A8x87w979wm/3ZmTrO/VCfIgHlG33iQ9+5RTcNvcffwZY5j3WvsxCtxjEMWwEapz/QCvRSLKq60IlxX0L/d/FnIU/rV9KrmqTDZ9XbZWo=
